### ISSUE TITLE
Problèmes d'affichage de fiches

### ISSUE THREAD

**Issue by marcel-lavergne** [guillaumebdx/bordeaux-202009-php-cheatsheet#114]
Les fiches n'ayant pas de vote affichés ne fonctionnent pas.

**Comment by marcel-lavergne** [comment]
Elles fonctionnent si on à au préalable cliqué sur le bouton de + de la catégorie "les plus populaires".

**Comment by vladsolntsev** [comment]
Merci Marcel! :)
