### ISSUE TITLE
Création de fiche vide et message d'erreur

### ISSUE THREAD

**Issue by victorcdrdm** [guillaumebdx/bordeaux-202009-php-cheatsheet#117]
Il est possible de crée une fiche sans remplir le moindre champs .
Le message d'erreur suite a une mauvaise recherche n'est pas très visible.

bon courage

**Comment by kozmarti** [comment]
Merci beaucoup pour ta note Victor,  le problème est résolu :)

**Comment by kozmarti** [comment]
Merci beaucoup pour ton note Victor, le problème est résolu :)
